version: '3.8'
services:
#  db:
#    image: postgres:latest
#    container_name: postgres_container
#    environment:
#      POSTGRES_USER: ${DB_USER}
#      POSTGRES_PASSWORD: ${DB_PASSWORD}
#      POSTGRES_DB: ${DB_NAME}
#    ports:
#      - "5432:5432"
#    healthcheck:
#      test: [ "CMD", "pg_isready", "-U", "robmoloney" ]
#      interval: 10s
#      retries: 5
#      start_period: 10s
#      timeout: 5s

  app:
    build: .
    container_name: spring_boot_app
    ports:
      - "8080:8080"
#    depends_on:
#      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}